/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/tWh2mIsPUf1
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import {
  Select,
  SelectTrigger,
  SelectValue,
  SelectContent,
  SelectItem,
} from "~/components/ui/select";
import { Switch } from "~/components/ui/switch";
import { Input } from "~/components/ui/input";
import { Button } from "~/components/ui/button";

export function LandingPage() {
  return (
    <div className="flex flex-col items-center w-full min-h-screen p-4 md:p-10">
      <header className="flex items-center w-full justify-between pb-4 border-b">
        <MenuIcon className="w-6 h-6" />
        <div className="flex items-center gap-4">
          <Select>
            <SelectTrigger className="text-muted-foreground">
              <SelectValue placeholder="Serif" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="serif">Serif</SelectItem>
              <SelectItem value="sans-serif">Sans Serif</SelectItem>
            </SelectContent>
          </Select>
          <Switch id="theme-toggle" />
        </div>
      </header>
      <main className="flex flex-col items-center w-full max-w-3xl mt-8 space-y-8">
        <form className="w-full">
          <div className="relative">
            <Input
              type="search"
              placeholder="keyboard"
              className="w-full pl-4 pr-10 py-2 rounded-full"
            />
            <SearchIcon className="absolute right-3 top-2.5 w-5 h-5 text-muted-foreground" />
          </div>
        </form>
        <div className="flex items-center w-full justify-between">
          <div>
            <h1 className="text-5xl font-bold">keyboard</h1>
            <p className="text-xl text-purple-600">/ˈkiːbɔːrd/</p>
          </div>
          <Button
            variant="ghost"
            size="icon"
            className="rounded-full bg-purple-100 text-purple-600"
          >
            <PlayIcon className="w-8 h-8" />
          </Button>
        </div>
        <div className="w-full">
          <h2 className="text-xl font-semibold">noun</h2>
          <hr className="my-4 border-t border-muted-foreground" />
          <div className="space-y-2">
            <h3 className="text-lg font-semibold">Meaning</h3>
            <ul className="space-y-1">
              <li className="flex items-start space-x-2">
                <span className="text-purple-600">•</span>
                <p>
                  (etc.) A set of keys used to operate a typewriter, computer
                  etc.
                </p>
              </li>
              <li className="flex items-start space-x-2">
                <span className="text-purple-600">•</span>
                <p>A component of many instruments including</p>
              </li>
            </ul>
          </div>
        </div>
      </main>
    </div>
  );
}

function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  );
}

function PlayIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="6 3 20 12 6 21 6 3" />
    </svg>
  );
}

function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  );
}
